#network
bind 0.0.0.0
port 6379

#logging
daemonize no
loglevel notice
logfile ""
#security
protected-mode yes

#rdb
#save every hour if at least 1 change
save 3600 1
#save every 5 min if 100 changes
save 300 100
#save every minute if 10000 changes
save 60 10000

#aof
appendonly yes
appendfsync everysec

#maxmemory management
maxmemory 100mb
maxmemory-policy allkeys-lru

#turn off default user
user default off

#superuser
user superuser on >admin ~* &* +@all
#normal user
user muftin on >123 resetchannels ~muftin:* +@string +ping +del
user event on >event ~event:* +@string +ping +del
user comunities on >comunities ~comunities:* +@string +ping +del

# 1. bind untuk menentukan network address tempat redis menerima koneksi, 0.0.0.0 brati redis bisa menerima seluruh interface yg tersedia di dalam container

# 2.port untuk menentukan port redis di host:container default (6379)

# 3. daemonize untuk menonaktifkan daemonize biar berjalan di di front

# 4. loglevel untuk menentukan level detail log, untuk belajar awal cukup pakai notice

# 5. logfile "" brati redis tidak di arahkan untuk menulis log ke file tertentu

# 6. protected-mode untuk keamanan redis, membatu mencegah akses yg tidak smestinya ketika server memiliki koneksi yg rentan terbuka

# 7. rdb bekerja untuk membuat snapshot dataset redis ke disk.

# save 3600 1 -> 3600 detik + minimal 1 perubahan
# save 300 100 -> 300 detik + minimal 100 perubahan
# save 60 10000 -> 60 detik + minimal 10.000 perubahan


# 8. AOF

# appendonly yes, memcatat semua log perubahan write yg bisa di gunakan utnuk membangun kembali dataset redis untuk melakukan recovery

# appendfsync everysec, Redis melakukan fsync sekitar setiap satu detik

# 9. memory manajement

# maxmemory 100mb, Menetapkan batas memory untuk data Redis sebesar: 100 MB

# maxmemory-policy allkeys-lru, menetapkan kebijakan ketika mencapai batas max, allkeys-lru menghapus semua key yg paling terahir tidak di gunakan

# 10. mematikan user default

# 11. manajement user dari superuser sampai user pengelola data